version: '3.9'

volumes:
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
      - ./config/dashboards:/var/lib/grafana/dashboards
      - ./config/plugins:/var/lib/grafana/plugins
      - grafana_data:/var/lib/grafana
    env_file:
      - ./config.env
      - ./secrets.env
    networks:
      - back-tier
      - front-tier
